boke1/App/views.py
from datetime import datetime

from flask import Blueprint, render_template, request, session, redirect, url_for
from App.models import *

blue = Blueprint('blue', __name__)


# 首页
@blue.route('/')
def index():
    articles = Article.query.all()
    classifies = Classify.query.all()
    return render_template('home/index.html',articles=articles,classifies=classifies)

@blue.route('/share/')
def share():
    return render_template('home/share.html')

@blue.route('/list/')
def list():
    return render_template('home/list.html')

@blue.route('/about/')
def about():
    return render_template('home/about.html')

@blue.route('/gbook/')
def gbook():
    return render_template('home/gbook.html')

@blue.route('/info/')
def info():
    return render_template('home/info.html')

@blue.route('/infopic/')
def infopic():
    return render_template('home/infopic.html')


@blue.route('/classify/<id>/')
def classify(id):
    classify = Classify.query.get(id)
    articles = classify.articles
    classifies = Classify.query.all()
    return render_template('home/index.html',articles=articles,classifies=classifies)

@blue.route('/check_article/<id>/')
def check_article(id):
    article = Article.query.get(id)
    return render_template('home/neirong.html',article=article)

@blue.route('/add_press/<id>/',methods=['POST','GET'])
def add_press(id):
    if request.method == 'POST':
        content = request.form.get('content')
        date = datetime.now().strftime('%Y-%m-%d %X')
        press = Mypress()
        press.content=content
        press.date=date
        press.articles=id
        my_add(press)
        article = Article.query.get(id)

        print('sjdhf')

        return render_template('home/neirong.html',article=article)
    return render_template('home/neirong.html')


#后台
@blue.route('/admin/regist/',methods=['POST','GET'])
def admin_regist():
    if request.method == 'POST':
        username = request.form.get('username')
        userwd = request.form.get('userwd')
        userwd2= request.form.get('userwd2')

        user = User.query.filter_by(name = username).first()
        if user:
            return render_template('admin/regist.html',msg='用户名已存在')
        else:
            if userwd != userwd2:
                return render_template('admin/regist.html',msg='密码验证错误')

            user = User()
            user.name=username
            user.passwd=userwd
            my_add(user)
            return render_template('admin/login.html',msg='注册成功')


    return render_template('admin/regist.html')



@blue.route('/admin/login/',methods=['POST','GET'])
def admin_login():
    if request.method == "POST":
        username = request.form.get('username')
        userwd = request.form.get('userwd')
        user = User.query.filter_by(name=username).first()
        if user:
            if userwd == user.passwd:
                session['username'] = user.name
                return render_template('admin/index.html', username=username)
            else:
                return "密码错误"
        else:
            return "用户不存在"
    return render_template('admin/login.html')

@blue.route('/admin/logout/')
def admin_logout():
    session.pop('username')
    return redirect(url_for('blue.admin_login'))

@blue.route('/admin/index/')
def admin_index():
    username = session.get('username','0')
    return render_template('admin/index.html',username=username)

@blue.route('/admin/article/',methods=['POST',"GET"])
def admin_article():
    username = session.get('username','0')
    articles = Article.query.all()
    return render_template('admin/article.html',articles=articles,username=username)

@blue.route('/admin/notice/')
def admin_notice():
    username = session.get('username','0')
    return render_template('admin/notice.html',username=username)

@blue.route('/admin/comment/')
def admin_comment():
    username = session.get('username','0')
    mypress = Mypress.query.all()
    # for i in mypress:
    #     print(i.my_article.id)
    return render_template('admin/comment.html',username=username,mypress=mypress)

@blue.route('/admin/category/')
def admin_category():
    username = session.get('username','0')
    classifies = Classify.query.all()
    return render_template('admin/category.html',username=username,classifies=classifies)

@blue.route('/admin/flink/')
def admin_flink():
    username = session.get('username','0')
    render_template('admin/flink.html',username=username)

@blue.route('/admin/manage-user/')
def admin_manage_user():
    username = session.get('username','0')
    return render_template('admin/manage-user.html',username=username)

@blue.route('/admin/loginlog/')
def admin_loginlog():
    username = session.get('username','0')
    return render_template('admin/loginlog.html',username=username)

@blue.route('/admin/setting/')
def admin_setting():
    username = session.get('username','0')
    return render_template('admin/setting.html',username=username)

@blue.route('/admin/readset/')
def admin_readset():
    username = session.get('username','0')
    return render_template('admin/readset.html',username=username)

@blue.route('/admin/add-notice/')
def admin_add_notice():
    username = session.get('username','0')
    return render_template('admin/add-notice.html',username=username)

@blue.route('/admin/update-article/<id>/',methods=['POST',"GET"])
def admin_update_article(id):
    username = session.get('username','0')
    if request.method == 'POST':
        title = request.form.get('title')
        context = request.form.get('context')
        tag = request.form.get('tag')
        classify = request.form.get('classify')
        date = datetime.now().strftime('%Y-%m-%d %X')
        article = Article.query.get(id)
        article.context = context
        article.title = title
        article.tag = tag
        article.date = date
        classify = Classify.query.filter_by(name=classify).first()
        if article.myclassify != classify.id:
            article.myclassify = classify.id
            classify.mycount += int(1)
            Classify.query.get(article.myclassify).mycount -= int(1)
            # print(classify,article.myclassify,classify.count,Classify.query.filter_by(id=article.myclassify).first().count)
            my_update()
            return redirect(url_for('blue.admin_article', values='修改成功'))
        my_update()
        return redirect(url_for('blue.admin_article', values='修改成功'))
    article = Article.query.get(id)
    classifies = Classify.query.all()
    return render_template('admin/update-article.html', article=article, classifies=classifies, username=username)

@blue.route('/admin/update-category/<id>/',methods=['POST',"GET"])
def admin_update_category(id):
    username = session.get('username','0')
    if request.method=="POST":
        name = request.form.get('name')
        another_name = request.form.get('another_name')
        classify = Classify.query.get(id)
        classify.name=name
        classify.another_name=another_name
        my_update()
        return redirect(url_for('blue.admin_category',username=username))
    classify = Classify.query.get(id)
    return render_template('admin/update-category.html',username=username,classify=classify)


@blue.route('/admin/update-flink')
def admin_update_flink():
    username = session.get('username','0')
    return render_template('admin/update-flink.html',username=username)

@blue.route('/admin/add-flink/')
def admin_add_flink():
    username = session.get('username','0')
    return render_template('admin/add-flink.html',username=username)


@blue.route('/delete_classify/<id>/')
def delete_classify(id):
    classify=Classify.query.filter_by(id=id).first()
    my_delete(classify)
    return redirect(url_for('blue.admin_category'))

@blue.route('/delete_article/<id>/')
def delete_article(id):
    article=Article.query.filter_by(id=id).first()
    # classify = Classify.query.get(article.myclassify)
    # classify.mycount += int(1)
    my_delete(article)
    return redirect(url_for('blue.admin_article'))

@blue.route('/delete_press/<id>/')
def admin_delete_press(id):
    username = session.get('username','0')
    # if not username:
    #     return redirect(url_for('blue.admin_comment'))
    print('ok:',id)
    press=Mypress.query.filter_by(id=id).first()
    my_delete(press)
    mypress = Mypress.query.all()
    print('deleat ok',)
    return redirect(url_for('blue.admin_comment',mypress=mypress,username=username))

@blue.route('/add_category/',methods=['POST','GET'])
def add_category():
    username = session.get('username', '0')
    if request.method == 'POST':
        name = request.form.get('name')
        another_name = request.form.get('another_name')
        classify = Classify()
        classify.name=name
        classify.another_name=another_name
        my_add(classify)
        return redirect(url_for('blue.admin_category'))
    classifies = Classify.query.all()
    return render_template('admin/category.html', username=username, classifies=classifies)


@blue.route('/admin/add-article/',methods=['POST','GET'])
def admin_add_article():
    username = session.get('username','0')
    if request.method == 'POST':
        context = request.form.get('context')
        title = request.form.get('title')
        tag = request.form.get('tag')
        category = request.form.get('classify')

        # print(context,tag,title,category)
        classify = Classify.query.filter_by(name=category).first()
        id = classify.id
        print(id)
        # classify.mycount += int(1)
        date = datetime.now().strftime('%Y-%m-%d %X')

        article = Article(title=title,context=context,date=date,myclassify=id,tag=tag)
        print(article)
        my_add(article)
        return redirect(url_for('blue.admin_article'))
    else:
        classifies = Classify.query.all()
        return render_template('admin/add-article2.html',username=username,classifies=classifies)
@blue.route('/check_press/',methods=['POST','GET'])

boke1/App/templates/home/about.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>首页_杨青个人博客 - 一个站在web前端设计之路的女技术员个人博客网站</title>
<meta name="keywords" content="个人博客,杨青个人博客,个人博客模板,杨青" />
<meta name="description" content="杨青个人博客，是一个站在web前端设计之路的女程序员个人网站，提供个人博客模板免费资源下载的个人原创网站。" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="/static/home/css/base.css" rel="stylesheet">
<link href="/static/home/css/index.css" rel="stylesheet">
<link href="/static/home/css/m.css" rel="stylesheet">
<script src="/static/home/js/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript" src="/static/home/js/hc-sticky.js"></script>
<script type="text/javascript" src="/static/home/js/comm.js"></script>
<!--[if lt IE 9]>
<script src="js/modernizr.js"></script>
<![endif]-->
</head>
<body>
<header class="header-navigation" id="header">
  <nav><div class="logo"><a href="/">杨青个人博客</a></div>
    <h2 id="mnavh"><span class="navicon"></span></h2>
    <ul id="starlist">
      <li><a href="{{ url_for('blue.index') }}">网站首页</a></li>
      <li><a href="{{ url_for('blue.share') }}">我的相册</a></li>
      <li><a href="{{ url_for('blue.list') }}">我的日记</a></li>
      <li><a href="{{ url_for('blue.about') }}">关于我</a></li>
      <li><a href="{{ url_for('blue.gbook') }}">留言</a></li>
      <li><a href="{{ url_for('blue.info') }}">内容页</a></li>
      <li><a href="{{ url_for('blue.infopic') }}">内容页</a></li>
    </ul>
</nav>
</header>
<article>
  <aside class="l_box">
    <div class="about_me">
      <h2>关于我</h2>
      <ul>
        <i><img src="/static/home/images/4.jpg"></i>
        <p><b>杨青</b>，一个80后草根女站长！09年入行。一直潜心研究web前端技术，一边工作一边积累经验，分享一些个人博客模板，以及SEO优化等心得。</p>
      </ul>
    </div>
    <div class="wdxc">
      <h2>我的相册</h2>
      <ul>
        <li><a href="/"><img src="/static/home/images/7.jpg"></a></li>
        <li><a href="/"><img src="/static/home/images/8.jpg"></a></li>
        <li><a href="/"><img src="/static/home/images/9.jpg"></a></li>
        <li><a href="/"><img src="/static/home/images/10.jpg"></a></li>
        <li><a href="/"><img src="/static/home/images/11.jpg"></a></li>
        <li><a href="/"><img src="/static/home/images/12.jpg"></a></li>
      </ul>
    </div>
    <div class="search">
      <form action="/e/search/index.php" method="post" name="searchform" id="searchform">
        <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
        <input name="show" value="title" type="hidden">
        <input name="tempid" value="1" type="hidden">
        <input name="tbname" value="news" type="hidden">
        <input name="Submit" class="input_submit" value="搜索" type="submit">
      </form>
    </div>
    <div class="fenlei">
      <h2>文章分类</h2>
      <ul>
        <li><a href="/">学无止境（33）</a></li>
        <li><a href="/">日记（19）</a></li>
        <li><a href="/">慢生活（520）</a></li>
        <li><a href="/">美文欣赏（40）</a></li>
      </ul>
    </div>

    <div class="guanzhu">
      <h2>关注我 么么哒</h2>
      <ul>
        <img src="/static/home/images/wx.jpg">
      </ul>
    </div>
  </aside>
  <main class="r_box">
     <div class="about">
      <p>杨青，女，一个80后草根女站长！09年入行。一直潜心研究web前端技术，一边工作一边积累经验，分享一些个人博客模板，以及SEO优化等心得。我入行早，大家也亲切的叫我&ldquo;青姐&rdquo;。<br />
           <br />
            SEO奋斗了将近两年时间，个人博客网站百度排名也从之前的30页后，排到了第一页。期间有很多的不容易，但是都没有放弃过。入了这一行，就深深的喜欢上它。我喜欢一句话&ldquo;冥冥中该来则来，无处可逃&rdquo;。<br />
            <br />
    <img src="/static/home/images/1.jpg">        近几年我也发现个人博客排前几页的也有很多是我做过的模板，感谢各位站长的欣赏，我仔细看过他们的网站。他们在我原模板的基础上有修改，而且他们做的原创内容都是值得一读的。有时候甚至排名都超过了我个人博客网站的排名。<br />
            <br />
            现在很多人向我请教如何做好SEO，我想说的是，一是&ldquo;代码&rdquo;，一定要简单，布局要合理。二是&ldquo;内容&rdquo;，一定要有原创，伪原创也是可以的。三是&ldquo;持续&rdquo;，这是一个持续性过程，一定要有耐心，SEO不是马上生效的。<br />
            <br />
            自从入了这一行，也交到了不少朋友，QQ群也不断的壮大起来，280998807(交流群 <span style="color:#FF0000;">已满员</span>)&nbsp; 280998843（技术群），群里的小伙伴们也很积极的帮助新朋友解决问题，如果你想加入我们，这个大家庭的门，永远给你敞开！另外微信群已于2018.4.13日开通（已满100，只接受群主邀请，可加我个人微信进群 。我的个人微信号 yangqq_1987）</p>
          <br />
           <br />
            SEO奋斗了将近两年时间，个人博客网站百度排名也从之前的30页后，排到了第一页。期间有很多的不容易，但是都没有放弃过。入了这一行，就深深的喜欢上它。我喜欢一句话&ldquo;冥冥中该来则来，无处可逃&rdquo;。<br />
            <br />
    <img src="/static/home/images/1.jpg">        近几年我也发现个人博客排前几页的也有很多是我做过的模板，感谢各位站长的欣赏，我仔细看过他们的网站。他们在我原模板的基础上有修改，而且他们做的原创内容都是值得一读的。有时候甚至排名都超过了我个人博客网站的排名。<br />
            <br />
            现在很多人向我请教如何做好SEO，我想说的是，一是&ldquo;代码&rdquo;，一定要简单，布局要合理。二是&ldquo;内容&rdquo;，一定要有原创，伪原创也是可以的。三是&ldquo;持续&rdquo;，这是一个持续性过程，一定要有耐心，SEO不是马上生效的。<br />
            <br />
            自从入了这一行，也交到了不少朋友，QQ群也不断的壮大起来，280998807(交流群 <span style="color:#FF0000;">已满员</span>)&nbsp; 280998843（技术群），群里的小伙伴们也很积极的帮助新朋友解决问题，如果你想加入我们，这个大家庭的门，永远给你敞开！另外微信群已于2018.4.13日开通（已满100，只接受群主邀请，可加我个人微信进群 。我的个人微信号 yangqq_1987）</p>
          <br />
          <h2>About my blue</h2>
          &nbsp;
          <p>域 名：www.yangqq.com 创建于2011年01月12日&nbsp;</p>
          <br />
          <p>服务器：阿里云服务器&nbsp;&nbsp;<a href="https://promotion.aliyun.com/ntms/act/ambassador/sharetouser.html?userCode=8smrzoqa&amp;productCode=vm" target="_blank"><span style="color:#FF0000;"><strong>前往阿里云官网购买&gt;&gt;</strong></span></a></p>
          <br />
          <p>备案号：蜀ICP备11002373号-1</p>
          <br />
          <p>程 序：PHP 帝国CMS7.5</p>

     </div>
  </main>
</article>
<footer>
  <p>Design by <a href="http://www.yangqq.com" target="_blank">杨青个人博客</a> <a href="/">蜀ICP备11002373号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>
</body>
</html>

boke1/App/templates/home/add_press.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="" method="post">
    评论内容：<input style="width: 300px;height: 100px" type="text" name="content">
    <input style="color: orange;width: 100px;height: 50px;background-color: #00a0e9" type="submit" value="添加">
</form>
</body>
</html>

boke1/App/templates/home/check_article.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
   <div style="margin-left: 300px;margin-top:100px">
        <h3>题目：{{ article.title }}</h3>
        <p style="width: 400px">内容：{{ article.context }}</p>
        <p style="width: 150px">栏目：{{ article.my_classify }}</p>

         {% for press in article.my_press %}
         <p>
            评论内容：{{ press.content }}
        </p>
        <p>
            评论时间：{{ press.date }}
        </p>
       {% endfor %}
       <a style="color: orange;margin-bottom: 20px;padding: 20px  ;background-color: #00a0e9" href="{{ url_for("blue.add_press",id=article.id) }}">添加评论</a>
       <br>



        <form action="{{ url_for("blue.index") }}">
            <input style="margin-top: 50px;color: orange;width: 100px;height: 50px;background-color: #00a0e9" type="submit" value="返回首页">
        </form>
       <a href=""></a>
   </div>
</body>
</html>

boke1/App/templates/home/index.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>首页_个人博客网站</title>
<meta name="keywords" content="个人博客,个人博客,个人博客模板," />
<meta name="description" content="个人博客，是一个站在web前端设计之路的女程序员个人网站，提供个人博客模板免费资源下载的个人原创网站。" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="/static/home/css/base.css" rel="stylesheet">
<link href="/static/home/css/index.css" rel="stylesheet">
<link href="/static/home/css/m.css" rel="stylesheet">
<script src="/static/home/js/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript" src="/static/home/js/comm.js"></script>
<!--[if lt IE 9]>
<script src="/static/home/js/modernizr.js"></script>
<![endif]-->
</head>
<body>
<header class="header-navigation" id="header">
  <nav><div class="logo"><a href="/">我的个人博客</a></div>
    <h2 id="mnavh"><span class="navicon"></span></h2>
    <ul id="starlist">
      <li><a href="{{ url_for('blue.index') }}">网站首页</a></li>
      <li><a href="{{ url_for('blue.share') }}">我的相册</a></li>
      <li><a href="{{ url_for('blue.list') }}">我的日记</a></li>
      <li><a href="{{ url_for('blue.about') }}">关于我</a></li>
      <li><a href="{{ url_for('blue.gbook') }}">留言</a></li>
      <li><a href="{{ url_for('blue.info') }}">内容页</a></li>
      <li><a href="{{ url_for('blue.infopic') }}">内容页</a></li>
    </ul>
</nav>
</header>
<article>
  <aside class="l_box">
      <div class="about_me">
        <h2>关于我</h2>
        <ul>
          <i><img src="/static/home/images/4.jpg"></i>
          <p><b>faker</b>，一个90后草根女站长！19年入行。一直潜心研究python端技术，一边工作一边积累经验，分享一些个人博客模板，以及SEO优化等心得。</p>
        </ul>
      </div>
      <div class="wdxc">
        <h2>我的相册</h2>
        <ul>
          <li><a href="/"><img src="/static/home/images/7.jpg"></a></li>
          <li><a href="/"><img src="/static/home/images/8.jpg"></a></li>
          <li><a href="/"><img src="/static/home/images/9.jpg"></a></li>
          <li><a href="/"><img src="/static/home/images/10.jpg"></a></li>
          <li><a href="/"><img src="/static/home/images/11.jpg"></a></li>
          <li><a href="/"><img src="/static/home/images/12.jpg"></a></li>
        </ul>
      </div>
      <div class="search">
        <form action="/e/search/index.php" method="post" name="searchform" id="searchform">
          <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
          <input name="show" value="title" type="hidden">
          <input name="tempid" value="1" type="hidden">
          <input name="tbname" value="news" type="hidden">
          <input name="Submit" class="input_submit" value="搜索" type="submit">
        </form>
      </div>
      <div class="fenlei">
        <h2>文章分类</h2>
        <ul>
            {% for classify in classifies %}
                <li>
                    <a href="{{ url_for('blue.classify',id=classify.id) }}">{{ classify.name }}</a>
                    <a href="{{ url_for('blue.classify',id=classify.id) }}">({{ classify.mycount }})</a>
                </li>
            {% endfor %}
        </ul>
      </div>
       <div class="tuijian">
        <h2>站长推荐</h2>
        <ul>
          <li><a href="/">你是什么人便会遇上什么人</a></li>
          <li><a href="/">帝国cms 列表页调用子栏目，没有则不显示栏目名称</a></li>
          <li><a href="/">第二届 优秀个人博客模板比赛参选活动</a></li>
          <li><a href="/">个人博客模板《绅士》后台管理</a></li>
          <li><a href="/">你是什么人便会遇上什么人</a></li>
          <li><a href="/">帝国cms 列表页调用子栏目，没有则不显示栏目名称</a></li>
          <li><a href="/">第二届 优秀个人博客模板比赛参选活动</a></li>
          <li><a href="/">个人博客模板《绅士》后台管理</a></li>
        </ul>
      </div>
      <div class="links">
        <h2>友情链接</h2>
        <ul>
          <a href="http://www.yangqq.com">个人博客</a>
        </ul>
      </div>
      <div class="guanzhu">
        <h2>关注我 么么哒</h2>
        <ul>
          <img src="/static/home/images/wx.jpg">
        </ul>
      </div>
  </aside>
  <main class="r_box">
    <ul>
        {% for article in articles %}
            <li><i><a href="/"><img src="/static/home/images/1.jpg"></a></i>
                <h3><a href="{{ url_for('blue.check_article',id=article.id)}}">{{ article.title }}</a></h3>
                {{ article.context }}
             </li>
        {% endfor %}
    </ul>
  </main>
</article>
<footer>
  <p>Design by <a href="http://www.yangqq.com" target="_blank">个人博客</a> <a href="/">蜀ICP备11002373号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>
</body>
</html>

boke1/App/templates/home/neirong.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>首页_杨青个人博客 - 一个站在web前端设计之路的女技术员个人博客网站</title>
<meta name="keywords" content="个人博客,杨青个人博客,个人博客模板,杨青" />
<meta name="description" content="杨青个人博客，是一个站在web前端设计之路的女程序员个人网站，提供个人博客模板免费资源下载的个人原创网站。" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="/static/home/css/base.css" rel="stylesheet">
<link href="/static/home/css/index.css" rel="stylesheet">
<link href="/static/home/css/m.css" rel="stylesheet">
<script src="/static/home/js/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript" src="/static/home/js/hc-sticky.js"></script>
<script type="text/javascript" src="/static/home/js/comm.js"></script>
<!--[if lt IE 9]>
<script src="js/modernizr.js"></script>
<![endif]-->
</head>
<body>
<header class="header-navigation" id="header">
  <nav><div class="logo"><a href="/">杨青个人博客</a></div>
    <h2 id="mnavh"><span class="navicon"></span></h2>
    <ul id="starlist">
      <li><a href="{{ url_for('blue.index') }}">网站首页</a></li>
      <li><a href="{{ url_for('blue.share') }}">我的相册</a></li>
      <li><a href="{{ url_for('blue.list') }}">我的日记</a></li>
      <li><a href="{{ url_for('blue.about') }}">关于我</a></li>
      <li><a href="{{ url_for('blue.gbook') }}">留言</a></li>
      <li><a href="{{ url_for('blue.info') }}">内容页</a></li>
      <li><a href="{{ url_for('blue.infopic') }}">内容页</a></li>
    </ul>
</nav>
</header>
<article>
  <aside class="l_box">
    <div class="about_me">
      <h2>关于我</h2>
      <ul>
        <i><img src="/static/home/images/4.jpg"></i>
        <p><b>杨青</b>，一个80后草根女站长！09年入行。一直潜心研究web前端技术，一边工作一边积累经验，分享一些个人博客模板，以及SEO优化等心得。</p>
      </ul>
    </div>
    <div class="wdxc">
      <h2>我的相册</h2>
      <ul>
        <li><a href="/"><img src="/static/home/images/7.jpg"></a></li>
        <li><a href="/"><img src="/static/home/images/8.jpg"></a></li>
        <li><a href="/"><img src="/static/home/images/9.jpg"></a></li>
        <li><a href="/"><img src="/static/home/images/10.jpg"></a></li>
        <li><a href="/"><img src="/static/home/images/11.jpg"></a></li>
        <li><a href="/"><img src="/static/home/images/12.jpg"></a></li>
      </ul>
    </div>
    <div class="search">
      <form action="/e/search/index.php" method="post" name="searchform" id="searchform">
        <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
        <input name="show" value="title" type="hidden">
        <input name="tempid" value="1" type="hidden">
        <input name="tbname" value="news" type="hidden">
        <input name="Submit" class="input_submit" value="搜索" type="submit">
      </form>
    </div>
    <div class="fenlei">
      <h2>文章分类</h2>
      <ul>
        <li><a href="/">学无止境（33）</a></li>
        <li><a href="/">日记（19）</a></li>
        <li><a href="/">慢生活（520）</a></li>
        <li><a href="/">美文欣赏（40）</a></li>
      </ul>
    </div>

    <div class="guanzhu">
      <h2>关注我 么么哒</h2>
      <ul>
        <img src="/static/home/images/wx.jpg">
      </ul>
    </div>
  </aside>
  <main class="r_box">
     <div class="about">
         <p><h2>标题:{{ article.title }}</h2><br />
           <br />
         <p>内容:{{ article.context }}</p>
            </p>
          <br />
          <h2>栏目:{{ article.my_classify }}</h2>
          &nbsp;

         {% for press in article.my_press %}
         <p>
            评论内容：{{ press.content }}
        </p>
        <p>
            评论时间：{{ press.date }}
        </p>
       {% endfor %}
{#         <br>#}
{#        <a style="color: orange;margin-bottom: 20px;padding: 20px  ;background-color: #00a0e9" href="{{ url_for("blue.neirong",id=article.id) }}">添加评论</a>#}
{#        <br>#}
         <form action="{{ url_for("blue.add_press",id = article.id)}}" method="post">
            评论内容：<input style="width: 300px;height: 50px" type="text" name="content">
            <input style="color: #4443ff;width: 100px;height: 30px;background-color: #8A7DE9" type="submit" value="添加">
         </form>

          <p>域 名：www.yangqq.com 创建于2011年01月12日&nbsp;</p>
          <br />
          <p>服务器：阿里云服务器&nbsp;&nbsp;<a href="https://promotion.aliyun.com/ntms/act/ambassador/sharetouser.html?userCode=8smrzoqa&amp;productCode=vm" target="_blank"><span style="color:#FF0000;"><strong>前往阿里云官网购买&gt;&gt;</strong></span></a></p>
          <br />
          <p>备案号：蜀ICP备11002373号-1</p>
          <br />
          <p>程 序：PHP 帝国CMS7.5</p>

     </div>
  </main>
</article>
<footer>
  <p>Design by <a href="http://www.yangqq.com" target="_blank">杨青个人博客</a> <a href="/">蜀ICP备11002373号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>
</body>
</html>